#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  8 11:02:52 2018

@author: pamela
@purpose: create dataframe of basic color attributes of each game box
"""
import cv2
import matplotlib.pyplot as plt
import pickle
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np
import webcolors

fileObject = open('compiled_info','rb')
compiled_info = pickle.load(fileObject)
fileObject.close()

n_games = len(compiled_info)

col_names = ['id', 'saturation', 'mean_red', 'mean_green', 'mean_blue', 'dom_color', 'simple_color']
box_colors = pd.DataFrame(columns = col_names)

for game in range(148, n_games):
    
    id_tmp = compiled_info[game]['id']
    
    data_tmp = {}
    #d["id] = id
    file_name = "/media/pamela/Stuff/game_images/" + str(id_tmp) + ".jpg"
    #img_gray = cv2.imread(file_name, 0)#, cv2.COLOR_BGR2RGB)
    img_color = cv2.imread(file_name)
    if not img_color is None:
        RGB_img = cv2.cvtColor(img_color,cv2.COLOR_BGR2RGB)
        HSV_img = cv2.cvtColor(img_color, cv2.COLOR_BGR2HSV)
    
        sat = HSV_img[:,:,2].mean()
        
        b = RGB_img[:,:,1].mean()
        g = RGB_img[:,1,:].mean()
        r = RGB_img[1,:,:].mean()
    
        #find dominant color
        img = RGB_img.reshape((RGB_img.shape[0] * RGB_img.shape[1],3)) #represent as row*column,channel number
        clt = KMeans(n_clusters=1, n_jobs = 5) #cluster number
        clt.fit(img)
        dom_color_rgb = tuple(clt.cluster_centers_[0])
       # webcolors.rgb_to_name((105, 185, 224))
    
        actual_name, closest_name = get_colour_name(dom_color_rgb)
        simple_color = simplify_color(closest_name)
        
        box_colors.loc[len(box_colors)] = [game, sat, r, g, b, closest_name, simple_color]
 
    #hist = find_histogram(clt)
    #bar = plot_colors2(hist, clt.cluster_centers_)
    #plt.axis("off")
    #plt.imshow(bar)
    #plt.imshow(RGB_img)
    #plt.show()

#file_name = "/media/pamela/Stuff/BoardGameXMLs/compiled_info"# + str(game_ids[id]) + ".txt"
file_name = "box_colors"
fileObject = open(file_name,'wb') 
pickle.dump(box_colors,fileObject)   
fileObject.close()  
