#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  9 16:45:43 2018

@author: pamela
"""

import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

#plot x var- check for shape and collinearity
#plot y var
num_bins = 500
counts, bins, patches = plt.hist(success['users_per_yr'].dropna(), num_bins, range = [0, 200])
plt.ylim(0, 500)
plt.show()

#merge box_colors with success
all_var = pd.merge(box_colors, success, how = 'outer', on = 'id')
ids = [d['id'] for d in compiled_info]
ratings = [d['rating'] for d in compiled_info]
rating_vars = pd.DataFrame()
rating_vars['id'] = ids
rating_vars['ratings'] = ratings
all_var = pd.merge(all_var, rating_vars, on = 'id')

test = pd.DataFrame.plot(all_var)
all_var.plot.scatter('saturation', 'users_per_yr')
all_var.plot.bar('simple_color', 'users_per_yr')

plt.figure()
all_var['simple_color'].plot.box()
all_var['users_per_yr'].groupby(all_var['simple_color']).groups.keys()
all_var.groupby('simple_color')['users_per_yr'].mean()

color_dummies = pd.get_dummies(all_var['simple_color'])

#DF of predictor vars
Xvars = pd.DataFrame()
#Xvars['simple_color'] = all_var['simple_color']
Xvars['saturation'] = all_var['saturation']
Xvars['red'] = all_var['mean_red']

Xvars = Xvars.join(color_dummies)

X_train, X_test, y_train, y_test = train_test_split(Xvars, all_var['users_per_yr'], test_size = 0.2)
print(X_train.shape)

lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
predictions = lm.predict(X_test)
model.score(X_test, y_test)
