#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  9 16:45:43 2018

@author: pamela
"""

import pandas as pd
import pickle
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt




#plot x var- check for shape and collinearity
#plot y var
#num_bins = 500
counts, bins, patches = plt.hist(compiled_info['com'].dropna(), num_bins, range = [0, 200])
#plt.ylim(0, 500)
#plt.show()


test = pd.DataFrame.plot(all_var)
all_var.plot.scatter('saturation', 'users_per_yr')
all_var.plot.bar('simple_color', 'users_per_yr')

plt.figure()
all_var['simple_color'].plot.box()
all_var['users_per_yr'].groupby(all_var['simple_color']).groups.keys()
all_var.groupby('simple_color')['users_per_yr'].mean()

color_dummies = pd.get_dummies(all_var_success['simple_color'])



X_train, X_test, y_train, y_test = train_test_split(Xvars, all_var_clean['users_per_yr_y'], test_size = 0.2)
print(X_train.shape)

lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
predictions = lm.predict(X_test)
model.score(X_test, y_test)
