#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  9 16:17:20 2018

@author: pamela
@purpose: calculate response variable
"""

import pandas as pd

fileObject = open('Data/compiled_info','rb')
compiled_info = pickle.load(fileObject)
fileObject.close()
n_games = len(compiled_info)

col_names = ['id', 'year', 'no_users', 'users_per_yr']
success = pd.DataFrame(columns = col_names)

for game in range(n_games):
    id_tmp = compiled_info[game]['id'] 
    year_tmp = compiled_info[game]['year']
    users_tmp = compiled_info[game]['no_owned']
    try:
        users_per_year = int(users_tmp)/(2018-int(year_tmp))
    except (TypeError, ZeroDivisionError):
        users_per_year = None
        
    success.loc[len(success)] = [id_tmp, year_tmp, users_tmp, users_per_year]
    
fileObject  = open("Data/success", 'wb')
pickle.dump(success, fileObject)
fileObject.close()
